In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "employee": ["John", "Alice", "Bob", "Emma", "David", "Sophia"],
    "department": ["IT", "HR", "IT", "Finance", "HR", "Finance"],
    "salary": [60000, 50000, 70000, 80000, 55000, 75000]
})
df

  employee department  salary
0     John         IT   60000
1    Alice         HR   50000
2      Bob         IT   70000
3     Emma    Finance   80000
4    David         HR   55000
5   Sophia    Finance   75000

In [6]:
# group by department
# find total salary and average salary per department and number of employees per departnment
df.groupby("department").agg(
    total_salary = ("salary", "sum"),
    avg_salary = ("salary", "mean"),
    no_of_employees = ("employee", "count")
)

            total_salary  avg_salary  no_of_employees
department
Finance           155000     77500.0                2
HR                105000     52500.0                2
IT                130000     65000.0                2

In [ ]:
# saving the data to