In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("globalAirQuality.csv")
# To print data whose aqi > 100
df [ df['aqi'] > 100]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [5]:
# To get data whose aqi > 100 and temp > 30
df [ (df['aqi'] > 100) & (df['temperature'] > 30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [6]:
# Chaining -> Get only required datas after filtering
df [ (df['aqi'] > 100) & (df['tempertaure'] > 30)] [['city', 'aqi', 'temperature']]

KeyError: 'tempertaure'